[package]
name = "egui-tetra"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
copypasta = "0.7.1"
egui = "0.12.0"
open = "1.7.0"
tetra = { version = "0.6.4", default-features = false }
